// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Stoiximen.Infrastructure.EF.Context;

#nullable disable

namespace Stoiximen.Infrastructure.Migrations
{
    [DbContext(typeof(StoiximenDbContext))]
    [Migration("20250620222725_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Stoiximen.Domain.Models.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Subscriptions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Basic access to the platform.",
                            Name = "Basic Plan",
                            Price = 9.99m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Full access to all features.",
                            Name = "Premium Plan",
                            Price = 29.99m
                        });
                });

            modelBuilder.Entity("Stoiximen.Domain.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SubscriptionStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "1111 Vale to telegramId sou edw",
                            Name = "Tony rs",
                            SubscriptionStatus = 0
                        },
                        new
                        {
                            Id = "2222 Vale to telegramId sou edw",
                            Name = "Xaris tsel",
                            SubscriptionStatus = 0
                        },
                        new
                        {
                            Id = "23142353",
                            Name = "GN",
                            SubscriptionStatus = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
