// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Stoiximen.Infrastructure.EF.Context;

#nullable disable

namespace Stoiximen.Infrastructure.Migrations
{
    [DbContext(typeof(StoiximenDbContext))]
    partial class StoiximenDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Stoiximen.Domain.Models.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Subscriptions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 6, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SYSTEM",
                            Description = "Basic access to the platform.",
                            Name = "Basic Plan",
                            Price = 9.99m,
                            UpdatedAt = new DateTime(2025, 6, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "SYSTEM"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 6, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SYSTEM",
                            Description = "Full access to all features.",
                            Name = "Premium Plan",
                            Price = 29.99m,
                            UpdatedAt = new DateTime(2025, 6, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "SYSTEM"
                        });
                });

            modelBuilder.Entity("Stoiximen.Domain.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SubscriptionStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "1111 Vale to telegramId sou edw",
                            CreatedAt = new DateTime(2025, 6, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SYSTEM",
                            Name = "Tony rs",
                            SubscriptionStatus = 0,
                            UpdatedAt = new DateTime(2025, 6, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "SYSTEM"
                        },
                        new
                        {
                            Id = "2222 Vale to telegramId sou edw",
                            CreatedAt = new DateTime(2025, 6, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SYSTEM",
                            Name = "Xaris tsel",
                            SubscriptionStatus = 0,
                            UpdatedAt = new DateTime(2025, 6, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "SYSTEM"
                        },
                        new
                        {
                            Id = "8011353457",
                            CreatedAt = new DateTime(2025, 6, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SYSTEM",
                            Name = "GN",
                            SubscriptionStatus = 0,
                            UpdatedAt = new DateTime(2025, 6, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "SYSTEM"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
